### **Tensor**

In [ ]:
import torch

x = torch.tensor([1 , 2 , 3 , 4])
print(x)

tensor([1, 2, 3, 4])


In [ ]:
import torch

# Tensor دو بعدی 

x = torch.tensor([
    [1 , 2 , 3] ,
    [4 , 5 , 6]
])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [3]:
import torch 

# Tensor سه بعدی 

x = torch.tensor([
    [
        [1 , 2] ,
        [3 , 4]
    ] ,
    [
        [5 , 6] ,
        [7 , 8]
    ]
])
print(x)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


### **Shape**

In [4]:
import torch

x = torch.tensor([
    [1 , 2 , 3] ,
    [4 , 5 , 6]
])
print(x.shape)

torch.Size([2, 3])


```python
[3 , Heigh , width]
```

```python
[32 , 3 , Heigh , width]
```

### **dtype**

In [1]:
import torch

x = torch.tensor([1 , 2 , 3 ])
print(x.dtype)

torch.int64


### **reshape**

In [7]:
import torch

x = torch.tensor([
    [1 , 2 , 3] ,
    [4 , 5 , 6]
])
print(x)
print(x.shape)

y = x.reshape(3 , 2)
print(y)
print(y.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
torch.Size([3, 2])


In [10]:
import torch

x = torch.tensor([
    [1 , 2 , 3] ,
    [4 , 5 , 6]
])

y = x.reshape(6)
print(y)

tensor([1, 2, 3, 4, 5, 6])


**what's the meaning of CUDA available ?**

In [15]:
x = x.to("cuda")

print(x.device)

cuda:0


### **Resize**


```python
cat 1 ---> 300 * 281

cat 2 ---> 500 * 374
```

### **Transform**

In [ ]:
from torchvision import transforms , datasets

transform = transforms.Compose([
    transforms.Resize((224 , 224)) ,
    transforms.ToTensor()
])

train_dataset = datasets.ImageFolder(
    r"C:\Users\Maryam\Desktop\Cat_Dog_Classifier\dataset\train",
    transform=transform
)

### **DataLoader**

In [ ]:
from torch.utils.data import DataLoader 

images , labels = next(iter(DataLoader))

**یک کتابخانه برای نمایش تصاویر**

In [ ]:
import matplotlib.pyplot as plt

plt.imshow(Image)

plt.show()

### **Split**

In [ ]:
from torchvision import datasets
from torch.utils.data import random_split 

train_size = 20000
validation_size = 2500
test_size = 2500

train_dataset , validation_dataset , test_dataset = random_split(
    datasets ,
    [train_size , validation_size ,test_size]
) 

### **CNN** => 
```python
Convolutional Neural Network
``` 

In [ ]:
import torch.nn as nn

**1. nn.Module** :  پایه ی ساخت مدل های Pytorch

**2. nn.Conv2d** : لایه ای که ویژگی های تصویری رو استخراج میکنه

**3. nn.ReLU** : یک تابع فعالسازی که اجازه می دهد روابط غیر خطی را یاد بگیرد 

**4. nn.MaxPool2d** : ابعاد تصویر رو کاهش میده و ویژگی های مهم تر رو نگه میداره

**5. nn.Flatten** : تنسور چند بعدی را به یک بردار تبدیل می کند

**6. nn.Linear** : لایه ای که در نهایت برای تصمیم گیری استفاده می شود

In [ ]:
import torch.nn as nn


class CatDogCNN(nn.Module):
    
    def __init__(self):
            super().__init__()
    
            self.conv1 = nn.Conv2d(3, 16, 3)
            self.relu = nn.ReLU()

### **forward**

In [9]:
import torch.nn as nn


class CatDogCNN(nn.Module):
    
    def __init__(self):
            super().__init__()
    
            self.conv1 = nn.Conv2d(3, 16, 3)
            self.relu = nn.ReLU()
            self.pool = nn.MaxPool2d(2)
            
            self.conv2 = nn.Conv2d(16, 32, 3)
            self.relu2 = nn.ReLU()  
            self.pool2 = nn.MaxPool2d(2)
            
            self.flatten = nn.Flatten()
            
            self.fc1 = nn.Linear(93312 , 128)
            self.relu3 = nn.ReLU()
            self.fc2 = nn.Linear(128 , 2)
            
    def forward(self , x) :
       x = self.conv1(x)
       x = self.relu(x)
       x = self.pool(x)
       
       x = self.conv2(x)
       x = self.relu2(x)
       x = self.pool2(x)
       
       x = self.flatten(x)
       
       x = self.fc1(x)
       x = self.relu3(x)
       x = self.fc2(x)
       
       return x

import torch

model = CatDogCNN()

x = torch.randn(1, 3, 224, 224)

output = model(x)

print("Input shape:", x.shape)
print("Output shape:", output.shape)

Input shape: torch.Size([1, 3, 224, 224])
Output shape: torch.Size([1, 2])


### **Loss Function**

```python
real answer --> cat -> 0
                                       --> Loss -> اشتباه زیاد
Model prediction --> dog -> 1
``` 

```python
Loss -> Backward -> Gradient -> Optimizer -> Weight Update
```

```python
1. model(images)

2. criterion(output , labels)

3. loss.backward()

4. optimizer.step()

5. optimizer.zero_grand()
```